fix: await the result returned by resourceIndicators.useGrantedResource function, in resolve_resource.js
panva/node-oidc-provider pull request #1173
Opened 2022-01-03 17:50 UTC by Starrah

First, thank all the contributors for your effort in building this awesome project, which helps me a lot! During my usage, I found something that maybe a minor bug. 

The `features.resourceIndicators.useGrantedResource` function defined in the config can be async function. In fact, the default value for that is indeed an async function:
https://github.com/panva/node-oidc-provider/blob/2ba83954760017caca5fe0e96e8eee2d10061e9e/lib/helpers/defaults.js#L201-L206
However, when the function is called in `resolver_resource.js`, which is used to resolve the resource for a auth or token request, the value returned by `useGrantedResource` is not awaited:
https://github.com/panva/node-oidc-provider/blob/2ba83954760017caca5fe0e96e8eee2d10061e9e/lib/helpers/resolve_resource.js#L14
In my opinion, this is a bug, which makes the `useGrantedResource` configration have no effect, since !! a `Promise` will always equals to `true`.

Thank you for your review!

2022-01-03 18:40 UTC, panva requested changes
Nice catch!

Can you please update https://github.com/panva/node-oidc-provider/blob/main/test/resource_indicators/resource_indicators.config.js#L41-L43 to be an async function? That way this fix will actually be tested.

2022-01-04 07:55 UTC, Starrah commented
> Nice catch!
> 
> Can you please update https://github.com/panva/node-oidc-provider/blob/main/test/resource_indicators/resource_indicators.config.js#L41-L43 to be an async function? That way this fix will actually be tested.

Updated the test with c35396a (force-pushed).

2022-01-04 08:27 UTC, panva approved these changes

2022-01-04 09:17 UTC, merged

2022-01-04 09:18 UTC, panva commented
@Starrah thank you for your contribution! I'd be interested in learning about your use of oidc-provider and the resourceIndicators feature and welcome any further contribution you might have to e.g. to documentation that was difficult to process.